#	General information
[package]
name = "kfs"
version = "0.1.0"
edition = "2021"
authors = ["lmartin <lmartin@student.42.fr>", "nieyraud <nieyraud@student.42.fr>"]

[[bin]]
name='kernel'
path='srcs/main.rs'
test = true

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
panic = "abort"

#	Dependencies
[dependencies]
