[package]
name = "alloc"
version = "0.1.0"
edition = "2021"

[lib]
name="alloc"
path="src/lib.rs"

[[example]]
name="test"

[[example]]
name="foo"
#

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
