name: kfs CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt-get update -y
    - name: Install rust
      run: curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Check format
      run: cargo fmt --all --check

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt-get update -y
    - name: Install cross-compiling toolchain
      run: ./config/setup_env.sh && echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Testing
      run: make test
