name: kfs CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt-get update -y
    - name: Install cross-compiling toolchain
      run: ./config/setup_env.sh && echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Testing
      run: make test
