name: kfs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cross-compiling toolchain
      run: ./config/setup_env.sh && echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Testing
      run: make test
