name: kfs CI

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ ci-test ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: setup env
      run: sudo apt-get update && \
           sudo apt-get install make nasm ca-certificates curl gnupg lsb-release && \
           sudo mkdir -p /etc/apt/keyrings && \
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
           echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
           $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
           sudo apt-get update && \
           sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
    - name: make Kernel
      run: sudo make
